spring:
  application:
    name: autolift
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: sandbox
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    default-schema: sandbox
    schemas:
      - sandbox
      - campaign
      - customer
      - voucher
      - promotion
      - loyalty
    locations:
      - classpath:db/migration/sandbox
      - classpath:db/migration/campaign
      - classpath:db/migration/customer
      - classpath:db/migration/voucher
      - classpath:db/migration/promotion
      - classpath:db/migration/loyalty
  modulith:
    runtime:
      flyway:
        enabled: false