CREATE SCHEMA IF NOT EXISTS ml;

CREATE TABLE IF NOT EXISTS ml.BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT PRIMARY KEY,
    VERSION BIGINT,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    CONSTRAINT UQ_JOB_INSTANCE UNIQUE (JOB_NAME, JOB_KEY)
);

CREATE TABLE IF NOT EXISTS ml.BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT PRIMARY KEY,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    VERSION BIGINT,
    CREATE_TIME TIMESTAMP NULL,
    START_TIME TIMESTAMP NULL,
    END_TIME TIMESTAMP NULL,
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(20),
    EXIT_DESCRIPTION VARCHAR(2500),
    LAST_UPDATED TIMESTAMP NULL,
    JOB_CLAIM_NAME VARCHAR(100),
    CONSTRAINT FK_JOB_EXECUTION_JOB_INSTANCE FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES ml.BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS ml.BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_TYPE VARCHAR(100) NOT NULL,
    PARAMETER_VALUE VARCHAR(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT PK_JOB_EXECUTION_PARAMS PRIMARY KEY (JOB_EXECUTION_ID, PARAMETER_NAME),
    CONSTRAINT FK_JOB_EXEC_PARAMS_JOB_EXEC FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES ml.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS ml.BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT PRIMARY KEY,
    VERSION BIGINT,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NULL,
    START_TIME TIMESTAMP NULL,
    END_TIME TIMESTAMP NULL,
    STATUS VARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(20),
    EXIT_DESCRIPTION VARCHAR(2500),
    LAST_UPDATED TIMESTAMP NULL,
    CONSTRAINT FK_STEP_EXEC_JOB_EXEC FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES ml.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS ml.BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT PK_STEP_EXECUTION_CONTEXT PRIMARY KEY (STEP_EXECUTION_ID),
    CONSTRAINT FK_STEP_EXEC_CTX_STEP_EXEC FOREIGN KEY (STEP_EXECUTION_ID) REFERENCES ml.BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS ml.BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT PK_JOB_EXECUTION_CONTEXT PRIMARY KEY (JOB_EXECUTION_ID),
    CONSTRAINT FK_JOB_EXEC_CTX_JOB_EXEC FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES ml.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE INDEX IF NOT EXISTS IDX_JOB_EXEC_INST_ID ON ml.BATCH_JOB_EXECUTION(JOB_INSTANCE_ID);
CREATE INDEX IF NOT EXISTS IDX_JOB_EXEC_STATUS ON ml.BATCH_JOB_EXECUTION(STATUS);